Fix perl validators outstanding error messages
ualbertalib/oaisys pull request #48
Opened 2020-10-23 20:05 UTC by ConnorSheremeta

https://github.com/ualbertalib/jupiter/issues/1888

2020-11-24 19:55 UTC, ConnorSheremeta commented
Testing status on this PR:
(only failing test is the base url test which will pass once it is on prod)

```
# RUNNING VALIDATION FOR https://era-app-stg-1.library.ualberta.ca/oai

### Checking Identify response

REQUEST: https://era-app-stg-1.library.ualberta.ca/oai?verb=Identify GET
PASS:    Administrator email address is 'eraadmi@ualberta.ca'
PASS:    Correctly reports OAI-PMH protocol version 2.0
FAIL:    baseURL supplied 'https://era-app-stg-1.library.ualberta.ca/oai' does not match the baseURL in the Identify response 'https://era.library.ualberta.ca/oai'. The baseURL you enter must EXACTLY match the baseURL returned in the Identify response. It must match in case (http://Wibble.org/ does not match http://wibble.org/) and include any trailing slashes etc.
PASS:    Datestamp granularity is 'seconds'
PASS:    Extracted earliestDatestamp 2018-06-22T13:06:50Z

### Checking ListSets response

REQUEST: https://era-app-stg-1.library.ualberta.ca/oai?verb=ListSets GET
PASS:    responseDate has correct format: 2020-11-24T19:38:37Z
PASS:    Extracted 150 set names: { f7766168-d234-491a-b27c-2c4a5eecbc99:d3a71855-d041-49b3-82f5-4aa68157ec90 7122b33b-fd7f-47bc-ae7c-89ad8acdd228:98c5ba80-9b0b-4319-8521-197f7db135c4 7122b33b-fd7f-47bc-ae7c-89ad8acdd228:f57b2cca-8e72-4625-91d2-9698ee4dd0bf ... }, will use setSpec &set=f7766168-d234-491a-b27c-2c4a5eecbc99:d3a71855-d041-49b3-82f5-4aa68157ec90 in tests

### Checking ListIdentifiers response

REQUEST: https://era-app-stg-1.library.ualberta.ca/oai?verb=ListIdentifiers&metadataPrefix=oai_dc&set=f7766168-d234-491a-b27c-2c4a5eecbc99:d3a71855-d041-49b3-82f5-4aa68157ec90 GET
PASS:    responseDate has correct format: 2020-11-24T19:38:38Z
PASS:    Good ListIdentifiers response, extracted id 'oai:era.library.ualberta.ca:0e82ba2c-a255-4241-bdfc-27efd0056268' for use in future tests.

### Checking ListMetadataFormats response

REQUEST: https://era-app-stg-1.library.ualberta.ca/oai?verb=ListMetadataFormats&identifier=oai%3Aera%2Elibrary%2Eualberta%2Eca%3A0e82ba2c-a255-4241-bdfc-27efd0056268 GET
PASS:    responseDate has correct format: 2020-11-24T19:38:39Z
PASS:    Good ListMetadataFormats response, includes oai_dc
PASS:    Data provider supports oai_dc metadataPrefix

### Checking GetRecord response

REQUEST: https://era-app-stg-1.library.ualberta.ca/oai?verb=GetRecord&identifier=oai%3Aera%2Elibrary%2Eualberta%2Eca%3A0e82ba2c-a255-4241-bdfc-27efd0056268&metadataPrefix=oai_dc GET
PASS:    responseDate has correct format: 2020-11-24T19:38:40Z
PASS:    Datestamp in GetRecord response (2020-11-18T18:15:49Z) has the correct form for seconds granularity.
PASS:    Datestamp in GetRecord response (2020-11-18T18:15:49Z) matched the seconds granularity specified in the Identify response.
PASS:    Expected setSpec was returned in the response

### Checking ListRecords response

REQUEST: https://era-app-stg-1.library.ualberta.ca/oai?verb=ListRecords&from=2020-11-18T18:15:49Z&until=2020-11-18T18:15:49Z&metadataPrefix=oai_dc GET
PASS:    responseDate has correct format: 2020-11-24T19:38:41Z
PASS:    Response is well formed
PASS:    ListRecords response correctly included record with identifier oai:era.library.ualberta.ca:0e82ba2c-a255-4241-bdfc-27efd0056268

### Checking exception handling (errors)

REQUEST: https://era-app-stg-1.library.ualberta.ca/oai?junk GET
PASS:    Error response correctly includes error code 'badVerb'
REQUEST: https://era-app-stg-1.library.ualberta.ca/oai?verb=junk GET
PASS:    Error response correctly includes error code 'badVerb'
REQUEST: https://era-app-stg-1.library.ualberta.ca/oai?verb=GetRecord&metadataPrefix=oai_dc GET
PASS:    Error response correctly includes error code 'badArgument'
REQUEST: https://era-app-stg-1.library.ualberta.ca/oai?verb=GetRecord&identifier=oai:era.library.ualberta.ca:0e82ba2c-a255-4241-bdfc-27efd0056268 GET
PASS:    Error response correctly includes error code 'badArgument'
REQUEST: https://era-app-stg-1.library.ualberta.ca/oai?verb=GetRecord&identifier=invalid"id&metadataPrefix=oai_dc GET
PASS:    Error response correctly includes error code 'idDoesNotExist'
REQUEST: https://era-app-stg-1.library.ualberta.ca/oai?verb=ListIdentifiers&until=junk GET
PASS:    Error response correctly includes error code 'badArgument'
REQUEST: https://era-app-stg-1.library.ualberta.ca/oai?verb=ListIdentifiers&from=junk GET
PASS:    Error response correctly includes error code 'badArgument'
REQUEST: https://era-app-stg-1.library.ualberta.ca/oai?verb=ListIdentifiers&resumptionToken=junk&until=2000-02-05 GET
PASS:    Error response correctly includes error code 'badResumptionToken'
REQUEST: https://era-app-stg-1.library.ualberta.ca/oai?verb=ListRecords&metadataPrefix=oai_dc&from=junk GET
PASS:    Error response correctly includes error code 'badArgument'
REQUEST: https://era-app-stg-1.library.ualberta.ca/oai?verb=ListRecords&resumptionToken=junk GET
PASS:    Error response correctly includes error code 'badResumptionToken'
REQUEST: https://era-app-stg-1.library.ualberta.ca/oai?verb=ListRecords&metadataPrefix=oai_dc&resumptionToken=junk&until=1990-01-10 GET
PASS:    Error response correctly includes error code 'badResumptionToken'
REQUEST: https://era-app-stg-1.library.ualberta.ca/oai?verb=ListRecords&metadataPrefix=oai_dc&until=junk GET
PASS:    Error response correctly includes error code 'badArgument'
REQUEST: https://era-app-stg-1.library.ualberta.ca/oai?verb=ListRecords GET
PASS:    Error response correctly includes error code 'badArgument'
PASS:    All 13 error requests properly handled

### Checking for version 2.0 specific exceptions

REQUEST: https://era-app-stg-1.library.ualberta.ca/oai?verb=ListRecords&metadataPrefix=oai_dc&from=2002-02-05&until=2002-02-06T05:35:00Z GET
PASS:    Error response correctly includes error code 'badArgument'
REQUEST: https://era-app-stg-1.library.ualberta.ca/oai?verb=ListRecords&metadataPrefix=oai_dc&until=2017-06-22T13:06:50Z GET
PASS:    Error response correctly includes error code 'noRecordsMatch'

### Checking that HTTP POST requests are handled correctly

REQUEST: https://era-app-stg-1.library.ualberta.ca/oai POST verb:Identify
PASS:    POST test 1 for Identify was successful
REQUEST: https://era-app-stg-1.library.ualberta.ca/oai POST identifier:oai:era.library.ualberta.ca:0e82ba2c-a255-4241-bdfc-27efd0056268 metadataPrefix:oai_dc verb:GetRecord
PASS:    POST test 2 for GetRecord was successful

### Checking for correct use of resumptionToken (if used)

REQUEST: https://era-app-stg-1.library.ualberta.ca/oai?verb=ListRecords&metadataPrefix=oai_dc GET
NOTE:    Got resumptionToken BJvjnpGPf77llhtQOXY7jd
REQUEST: https://era-app-stg-1.library.ualberta.ca/oai?verb=ListRecords&resumptionToken=BJvjnpGPf77llhtQOXY7jd GET
PASS:    Resumption tokens appear to work

## Validation status of data provider https://era-app-stg-1.library.ualberta.ca/oai is FAILED
```

2020-12-23 23:52 UTC, mbarnett requested changes

2020-12-23 23:52 UTC, mbarnett commented on app/controllers/oaisys/pmh_controller.rb
> +      when 1
Just leaving a note here for January about what we discussed re: replacing these ints with meaningful symbols to make this a bit clearer to the reader

2021-01-26 00:25 UTC, mbarnett approved these changes

2021-01-26 18:29 UTC, merged